apiVersion: v1
kind: PersistentVolume
metadata:
  name: main-pv
  labels:
    volume-type: plex-storage
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /plex-storage
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubenode01
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: microk8s-hostpath
  volumeMode: Filesystem
