apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
        storage: 10Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
