apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-tv-storage
  namespace: plex
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath
