apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-storage-pvc
  namespace: plex
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #storageClassName: microk8s-hostpath
  selector:
    matchLabels:
      volume-type: plex-storage