image:
  repository: ghcr.io/k8s-at-home/plex
  tag:
  pullPolicy: IfNotPresent

env:
  TZ: "Australia/Brisbane"
  PLEX_PREFERENCE_1: "DlnaEnabled=1"
  PLEX_PREFERENCE_2: "FriendlyName=plex-local"
  PLEX_PREFERENCE_3: "allowMediaDeletion=1"
  PLEX_PREFERENCE_4: "FSEventLibraryUpdatesEnabled=1"
  ADVERTISE_IP: "http://192.168.1.210"
  # ALLOWED_NETWORKS:
  #PLEX_CLAIM: "claim-yxLmmUTzivmJs9x97Ys6"
  # PLEX_PREFERENCE_1: "FriendlyName=plex-kubernetes"
  # PLEX_PREFERENCE_2: "EnableIPv6=0"
  # PLEX_PREFERENCE_3: "logDebug=0"
  # PLEX_PREFERENCE_4: "DisableTLSv1_0=1"
  # PLEX_PREFERENCE_5: "LanNetworksBandwidth=xxx.xxx.xxx.0/18\,xxx.xxx.xxx.0/24\,xxx.xxx.xxx.0/24"
  # PLEX_PREFERENCE_6: "TranscoderQuality=2"
  # PLEX_PREFERENCE_7: "TreatWanIpAsLocal=0"
  # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"

service:
  main:
    primary: true
    ports:
      http:
        port: 32400
  dnla-tcp:
    enabled: false
    type: NodePort
    ports:
      dnla-tcp:
        enabled: true
        port: 32469
        protocol: TCP
        targetPort: 32469
    externalTrafficPolicy: Local
  dnla-udp:
    enabled: false
    type: NodePort
    ports:
      dnla-udp:
        enabled: true
        port: 1900
        protocol: TCP
        targetPort: 1900
    externalTrafficPolicy: Local

ingress:
  main:
    enabled: true
    hosts:
      - host: "plex.local"
        paths:
        - path: /
          pathType: Prefix
          service:
            name:
            port: 32400

hostNetwork: false

persistence:
  movie-storage:
    enabled: true
    type: pvc
    mountPath: /plex-movies
    accessMode: ReadWriteOnce    
    size: 10Gi
  config:
    enabled: true
    mountPath: /config
    size: 1Gi

  transcode:
    enabled: false
    mountPath: /transcode
  
podSecurityContext: {}

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 2048Mi
